namespace Myc.Core.Commands;

public enum MycCommand
{
    Help,
    Rename,
    View,
    Edit,
    Copy,
    Move,
    MakeDirectory,
    Delete,
    PermanentDelete,
    Menu,
    Quit,
    Refresh,
    ClearMarks,
    SwitchPanel,
    Mark,
    MoveCursor,
    EnterDirectory,
    ParentDirectory,
    Activate,
    SortName,
    SortExtension,
    SortSize,
    SortModified,
    ToggleHidden,
    SelectPattern,
    DeselectPattern,
    InvertSelection,
    SelectAll,
    GoToPath,
    SameDirectory,
    SwapPanels,
    Reveal,
}
